- name: Push syncthing gathering fact on clients
  copy:
    src: syncthing.fact
    dest: /etc/ansible/facts.d/
    mode: 0500
    owner: root
  register: syncthing_gathering_fact

- name: reload ansible_local
  setup: filter=ansible_local
  when: syncthing_gathering_fact.changed

#- debug:
#    msg: "{{ syncthing_config }}"
#  changed_when: true

- action: syncthing_validate

- action: syncthing_init

- name: Install syncthing dependencies
  package:
    name: "{{ syncthing_config.packages }}"

- name: enforces service directories
  file:
    state: directory
    path: "{{ item }}"
    owner: syncthing
    mode: 0700
  loop: "{{ syncthing_config.folders_to_create }}"

- name: enforces config file
  template:
    src: config.xml
    dest: "{{ syncthing_config.config_path }}"
    owner: "{{ syncthing_config.user_group }}"
    mode: 0640
  notify: restart syncthing

- name: start and enables service
  service:
    name: syncthing
    enabled: yes
    state: started

- name: reload ansible_local
  setup: filter=ansible_local
  when: syncthing_gathering_fact.changed

- name: enforces config file
  template:
    src: config.xml
    dest: "{{ syncthing_config.config_path }}"
    owner: "{{ syncthing_config.user_group }}"
    mode: 0640
  when: syncthing_gathering_fact.changed
  notify: restart syncthing
